# docker build -t ec2-deploy.base -f Dockerfile.base .
# 최소 용량으로 시작하기 위해 -slim으로 시작
FROM        python:3.6.4-slim

RUN         apt-get -y update
RUN         apt-get -y dist-upgrade
RUN         apt-get -y install nginx supervisor
# slim으로 빌드할 경우, uWSGI설치를 위해 필요한 패키지
RUN         apt-get -y install build-essential

COPY        . /srv/project
WORKDIR     /srv/project
RUN         pip install -r requirements.txt
